name: CI/CD Pipeline
on: 
push:
branches: ["main"]

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
- name: Chekout Code
- uses: actions/checkout@v3

- name: Build step 
- run: echo "Building project..."

- name: Test step
- runs: echo "Testing tests..."

- name: Deploy steo
- run: echo "Deploying project..."
